
version: 2

models:
    - name: FACT_JBUFlights
      description: "This table stores the output from Open Sky's STATESALL endpoint /
      located here: https://opensky-network.org/api/states/all

      The endpoint is called once per minute, and the data in the table updates at 10 minute intervals"

      columns:
          - name: icao24
            description: "Unique ICAO 24-bit address of the transponder in hex string representation."
            tests:
                - not_null

          - name: flightcarriercode
            description: "Indicates the flight carrier. Taken from the first 3 characters of the callsign."

          - name: flightnumber
            description: "Flight number, derived from the last 4 digits of the callsign."


          - name: origin_country
            description: "Country name inferred from the ICAO 24-bit address."
            tests:
                - not_null

          - name: last_position_update
            description: "Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s."
            tests:
                - not_null

          - name: last_update
            description: "Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder."
            tests:
                - not_null

          - name: longitude
            description: "WGS-84 longitude in decimal degrees. Can be null."

          - name: latitude
            description: "WGS-84 latitude in decimal degrees. Can be null."

          - name: baro_altitude
            description: "Barometric altitude in meters. Can be null."

          - name: geo_altitude
            description: "Geometric altitude in meters. Can be null."

          - name: on_ground
            description: "Boolean value which indicates if the position was retrieved from a surface position report."
            tests:
                - not_null

          - name: velocity
            description: "Velocity over ground in m/s. Can be null."

          - name: true_track
            description: "True track in decimal degrees clockwise from north (north=0°). Can be null."

          - name: vertical_rate
            description: "Vertical rate in m/s. A positive value indicates that the airplane is climbing, a negative value indicates that it descends. Can be null."

          - name: sensors
            description: "IDs of the receivers which contributed to this state vector. Is null if no filtering for sensor was used in the request."

          - name: squawk
            description: "The transponder code aka Squawk. Can be null."

          - name: spi
            description: "Whether flight status indicates special purpose indicator."

          - name: position_source
            description: "Origin of this state’s position: 0 = ADS-B, 1 = ASTERIX, 2 = MLAT"

          - name: API_CALLTIMESTAMP
            description: "The time that the API was called. This is measured in the number of seconds passed since epoch (Jan 1 1970) in Eastern time."

          - name: DATABASE_TIMESTAMP
            description: "The time that the record was inserted into OPENSKY.DBO.JBU_Flights"


    - name: RAW_JBUFlights
      description: "This table stores the output from Open Sky's STATESALL endpoint /
      located here: https://opensky-network.org/api/states/all

      The endpoint is called once per minute, and the data in the table updates at 10 minute intervals"

      columns:
          - name: icao24
            description: "Unique ICAO 24-bit address of the transponder in hex string representation."
            tests:
                - not_null

          - name: callsign
            description: "Callsign of the vehicle (8 chars). Can be null if no callsign has been received."

          - name: origin_country
            description: "Country name inferred from the ICAO 24-bit address."
            tests:
                - not_null

          - name: time_position
            description: "Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s."
            tests:
                - not_null

          - name: last_contact
            description: "Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder."
            tests:
                - not_null

          - name: longitude
            description: "WGS-84 longitude in decimal degrees. Can be null."

          - name: latitude
            description: "WGS-84 latitude in decimal degrees. Can be null."

          - name: baro_altitude
            description: "Barometric altitude in meters. Can be null."

          - name: on_ground
            description: "Boolean value which indicates if the position was retrieved from a surface position report."
            tests:
                - not_null

          - name: velocity
            description: "Velocity over ground in m/s. Can be null."

          - name: true_track
            description: "True track in decimal degrees clockwise from north (north=0°). Can be null."

          - name: vertical_rate
            description: "Vertical rate in m/s. A positive value indicates that the airplane is climbing, a negative value indicates that it descends. Can be null."

          - name: sensors
            description: "IDs of the receivers which contributed to this state vector. Is null if no filtering for sensor was used in the request."

          - name: geo_altitude
            description: "Geometric altitude in meters. Can be null."

          - name: squawk
            description: "The transponder code aka Squawk. Can be null."

          - name: spi
            description: "Whether flight status indicates special purpose indicator."

          - name: position_source
            description: "Origin of this state’s position: 0 = ADS-B, 1 = ASTERIX, 2 = MLAT"

          - name: API_CALLTIMESTAMP
            description: "The time that the API was called. This is measured in the number of seconds passed since epoch (Jan 1 1970) in Eastern time."

          - name: DATABASE_TIMESTAMP
            description: "The time that the record was inserted into OPENSKY.DBO.JBU_Flights"
